# Generated by Django 4.0.6 on 2022-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meal_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='profile',
            new_name='user',
        ),
    ]
