# Generated by Django 4.0.6 on 2022-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_profile_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default_food.jpg', upload_to='food_pics'),
        ),
    ]
