# Generated by Django 4.0.6 on 2022-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table='Meals',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profiles',
        ),
    ]
